### ISSUE TITLE
Some samples show non-zero inventory on first tick

### ISSUE THREAD

**Issue by minerllabs** [minerllabs/minerl#41] opened 2019-06-11 17:34 UTC
Some instances of `MineRLObtainDiamond-v0` show non-zero inventory for first time step where inventory should be empty

**Comment by brandonhoughton** [comment] 2019-06-11 20:57
Items persist when doing back to back experiments ... unsure of the root cause. Data will be re-published using the current inventory container rather than the player's local inventory which looks to resolve issue. ETA +24-48hr for re-publishing data =( New download will be required unless a clean way to patch is implemented

**Comment by albert-yue** [comment] 2019-06-15 05:05
Just wondering if this is resolved and we can redownload the data with the fix?

**Comment by minerllabs** [comment] 2019-06-17 05:45
It has been resolved - will be published with an updated environment very soon!

**Comment by brandonhoughton** [comment] 2019-06-18 05:59
Fixed with data version r2g1

**Closed by brandonhoughton** 2019-06-18 05:59 UTC
Labels: bug
