### ISSUE TITLE
Glaring, impactful bug

### ISSUE THREAD

**Issue by albertwujj** [minerllabs/minerl#51] opened 2019-06-14 08:25 UTC
Using the following script on Ubuntu 18.04 breaks:

```
import minerl
data = minerl.data.make('MineRLNavigateExtremeDense-v0')
pov_shape = (64,64,3)

for obs, rew, done, act in data.seq_iter(num_epochs=1, max_sequence_len=32):
    for x in obs['pov']:
        if x.shape != pov_shape:
            print(f'mineRL bug, pov shape: {x.shape}')
```

**Comment by albertwujj** [comment] 2019-06-15 00:24
May you please respond? The observation shape for 'pov' should clearly be (64, 64, 3), but if you run the above you'll see (at least on my computer), that it is sometimes (64*4, 64*3, 3). Do I need to update my mineRL install?

**Comment by MadcowD** [comment] 2019-06-15 14:06
@brandonhoughton Can you please address this. Even if you make a hotpatch for the data sequence iterator to ensure the correct data is drawn; we need to fix this. 

@albertwujj Oni t!

**Comment by MadcowD** [comment] 2019-06-15 16:56
Duplicate of #28 
Fix completed, will be released in the next `minerl` update.

**Comment by kaixin96** [comment] 2019-06-16 06:37
Same bug in "MineRLTreechop-v0" environment.
```python
(Pdb) obs['pov'].shape
(1, 192, 256, 3)
```

**Closed** 2019-06-17 20:57 UTC
Labels: bug, duplicate, fix pending
